//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompMain
    {
        public int CompID { get; set; }
        public string CompName { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Format { get; set; }
        public Nullable<System.DateTime> LeaguePosUpdate { get; set; }
        public int NumberOfPlayers { get; set; }
    }
}
