//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [MetadataType(typeof(CompScoreMd))]
    public partial class CompScore
    {
        public int CompScoreID { get; set; }
        public int? CompID { get; set; }
        public int CompPlayerID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> SSS { get; set; }
        public Nullable<int> Hole1 { get; set; }
        public Nullable<int> Hole2 { get; set; }
        public Nullable<int> Hole3 { get; set; }
        public Nullable<int> Hole4 { get; set; }
        public Nullable<int> Hole5 { get; set; }
        public Nullable<int> Hole6 { get; set; }
        public Nullable<int> Hole7 { get; set; }
        public Nullable<int> Hole8 { get; set; }
        public Nullable<int> Hole9 { get; set; }
        public Nullable<int> Hole10 { get; set; }
        public Nullable<int> Hole11 { get; set; }
        public Nullable<int> Hole12 { get; set; }
        public Nullable<int> Hole13 { get; set; }
        public Nullable<int> Hole14 { get; set; }
        public Nullable<int> Hole15 { get; set; }
        public Nullable<int> Hole16 { get; set; }
        public Nullable<int> Hole17 { get; set; }
        public Nullable<int> Hole18 { get; set; }
        public Nullable<decimal> PlayerHcap { get; set; }
        public Nullable<int> TotalPoints { get; set; }
        public Nullable<System.DateTime> RndDate { get; set; }
        public string TeeColour { get; set; }

        public SelectList TeeColourList()
        {
            return new SelectList(new string[] { "White", "Yellow", "Red" });
        }

    }

    public class CompScoreMd
    {
        [DisplayName("Course")]
        public int CourseID { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Round Date")]
        [Required(ErrorMessage = "Please enter the round date ..")]
        public Nullable<System.DateTime> RndDate { get; set; }

        [DisplayName("Tee Colour")]
        public string TeeColour { get; set; }

    }
}
