//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CourseDetailMd))]
    public partial class CourseDetail
    {
        public int CourseDetailID { get; set; }
        public int CourseID { get; set; }
        public int HoleNumber { get; set; }
        public Nullable<int> WhiteYrds { get; set; }
        public Nullable<int> YellowYrds { get; set; }
        public Nullable<int> MensPar { get; set; }
        public Nullable<int> MensSI { get; set; }
        public Nullable<int> RedYrds { get; set; }
        public Nullable<int> LadiesPar { get; set; }
        public Nullable<int> LadiesSI { get; set; }
    }

    public class CourseDetailMd
    {
        [DisplayName("Hole")]
        public int HoleNumber { get; set; }

        [DisplayName("White Yards")]
        public Nullable<int> WhiteYrds { get; set; }

        [DisplayName("Yellow Yards")]
        public Nullable<int> YellowYrds { get; set; }

        [DisplayName("Mens Par")]
        public Nullable<int> MensPar { get; set; }

        [DisplayName("Mens SI")]
        public Nullable<int> MensSI { get; set; }

        [DisplayName("Red Yards")]
        public Nullable<int> RedYrds { get; set; }

        [DisplayName("Ladies Par")]
        public Nullable<int> LadiesPar { get; set; }

        [DisplayName("Ladies SI")]
        public Nullable<int> LadiesSI { get; set; }
    }
}

