//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public int CourseDetailID { get; set; }
        public int CourseID { get; set; }
        public int HoleNumber { get; set; }
        public Nullable<int> WhiteYrds { get; set; }
        public Nullable<int> YellowYrds { get; set; }
        public Nullable<int> MensPar { get; set; }
        public Nullable<int> MensSI { get; set; }
        public Nullable<int> RedYrds { get; set; }
        public Nullable<int> LadiesPar { get; set; }
        public Nullable<int> LadiesSI { get; set; }
    }
}
