//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMain
    {
        public int CourseID { get; set; }
        public string ClubName { get; set; }
        public Nullable<int> WhiteSSS { get; set; }
        public Nullable<int> YellowSSS { get; set; }
        public Nullable<int> RedSSS { get; set; }
        public string ImagePath { get; set; }
    }
}
