//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreCardImage
    {
        public int ImageID { get; set; }
        public int CompID { get; set; }
        public string CardImage { get; set; }
        public Nullable<bool> Processed { get; set; }
        public string Note { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> RoundDate { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string TeeColour { get; set; }
        public Nullable<int> SSS { get; set; }
    }
}
