//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TigerLineScoresEntities1 : DbContext
    {
        public TigerLineScoresEntities1()
            : base("name=TigerLineScoresEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<CourseDetail> CourseDetails { get; set; }
        public virtual DbSet<CourseMain> CourseMains { get; set; }
        public virtual DbSet<CompMain> CompMains { get; set; }
        public virtual DbSet<CompPlayer> CompPlayers { get; set; }
        public virtual DbSet<CompScore> CompScores { get; set; }
        public virtual DbSet<ScoreCardImage> ScoreCardImages { get; set; }
        public virtual DbSet<UpcomingRnd> UpcomingRnds { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    }
}
