//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerLineScores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpcomingRnd
    {
        public int RndID { get; set; }
        public int CompPlayerID { get; set; }
        public int CompID { get; set; }
        public Nullable<System.DateTime> RndDate { get; set; }
        public string RndType { get; set; }
        public int CourseID { get; set; }
        public string Note { get; set; }
        public string CourseName { get; set; }
    }
}
